"""Advanced Features panels (Chat, Workflows, etc)."""
from .._components import (
    tab_panel,
)


def _chat() -> str:
    return (
        '<div id="tab-chat" class="card" style="display:none">\n'
        '  <div class="flex items-center justify-between mb-3">\n'
        '    <h3 class="text-lg font-semibold">&#x1f4ac; Agent Chat</h3>\n'
        '    <span id="chat-status" class="text-xs font-mono" style="color:var(--text-muted)">Ready</span>\n'
        "  </div>\n"
        '  <div class="grid grid-cols-1 md:grid-cols-3 gap-3 mb-3">\n'
        '    <div>\n'
        '      <label class="text-xs uppercase tracking-wide block mb-1" style="color:var(--text-muted)">Agent</label>\n'
        '      <select id="chat-agent"\n'
        '        class="w-full px-3 py-2 text-sm rounded-lg outline-none"'
        ' style="background:var(--surface-2);border:1px solid var(--border);color:var(--text-primary)">\n'
        '        <option value="cybersec-agent">cybersec-agent</option>\n'
        '      </select>\n'
        '    </div>\n'
        '    <div>\n'
        '      <label class="text-xs uppercase tracking-wide block mb-1" style="color:var(--text-muted)">Model</label>\n'
        '      <select id="chat-model"\n'
        '        class="w-full px-3 py-2 text-sm rounded-lg outline-none"'
        ' style="background:var(--surface-2);border:1px solid var(--border);color:var(--text-primary)">\n'
        '        <option value="">Auto</option>\n'
        '      </select>\n'
        '    </div>\n'
        '    <div style="display:flex;align-items:flex-end;gap:8px">\n'
        '      <button class="btn btn-accent flex-1" onclick="acChatSend()">Send</button>\n'
        '      <button class="btn btn-ghost flex-1" onclick="acChatClear()">Clear</button>\n'
        '    </div>\n'
        '  </div>\n'
        '  <div id="chat-messages" class="space-y-3 mb-3" style="height:400px;overflow-y:auto;border:1px solid var(--border);border-radius:8px;padding:12px"></div>\n'
        '  <textarea id="chat-input" placeholder="Message\u2026" class="w-full px-3 py-2 text-sm rounded-lg outline-none"'
        ' style="background:var(--surface-2);border:1px solid var(--border);color:var(--text-primary)" rows="3"></textarea>\n'
        '</div>\n'
    )


def _team_builder() -> str:
    _inp = 'style="padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px;font-family:var(--font-mono)"'
    _lbl = 'style="font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted);display:block;margin-bottom:4px"'
    return (
        '<div id="tab-team-builder" class="card" style="display:none">\n'
        '  <h3 style="font-size:1rem;font-weight:600;margin-bottom:14px">&#x1f465; Team Builder</h3>\n'
        '  <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px">\n'
        # Left: agent browser
        '    <div>\n'
        '      <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px">\n'
        '        <input id="tb-filter" placeholder="Filter agents…" oninput="tbFilterAgents(this.value)" ' + _inp + ' style="flex:1;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px"/>\n'
        '        <span id="tb-agent-count" style="font-size:12px;color:var(--text-muted);white-space:nowrap">0 agents</span>\n'
        '      </div>\n'
        '      <div id="tb-agents-table" style="max-height:280px;overflow-y:auto"></div>\n'
        '    </div>\n'
        # Right: skills browser
        '    <div>\n'
        '      <div style="display:flex;gap:8px;margin-bottom:8px">\n'
        '        <input id="tb-skill-q" placeholder="Filter skills…" oninput="tbLoadSkills()" ' + _inp + ' style="flex:1;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px"/>\n'
        '        <select id="tb-skill-domain" onchange="tbLoadSkills()" ' + _inp + ' style="padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px"><option value="">All domains</option></select>\n'
        '        <span id="tb-skill-count" style="font-size:12px;color:var(--text-muted);white-space:nowrap;align-self:center"></span>\n'
        '      </div>\n'
        '      <div id="tb-skills-table" style="max-height:280px;overflow-y:auto"></div>\n'
        '    </div>\n'
        '  </div>\n'
        # Team members
        '  <div style="margin-top:16px">\n'
        '    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:8px">\n'
        '      <h4 style="font-size:13px;font-weight:600">Team Members</h4>\n'
        '      <button class="btn" style="font-size:11px" onclick="tbAddMember()">+ Add Member</button>\n'
        '    </div>\n'
        '    <div id="tb-members" style="display:flex;flex-direction:column;gap:6px;min-height:40px;border:1px dashed var(--border);border-radius:var(--radius);padding:8px"></div>\n'
        '  </div>\n'
        # Preview + save
        '  <details style="margin-top:14px">\n'
        '    <summary style="cursor:pointer;font-size:12px;color:var(--text-muted)">Team JSON preview</summary>\n'
        '    <pre id="tb-team-json" style="margin-top:6px;padding:10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);font-size:11px;overflow-x:auto;white-space:pre-wrap;color:var(--text-primary)"></pre>\n'
        '  </details>\n'
        '  <div style="display:flex;align-items:center;gap:10px;margin-top:12px">\n'
        '    <label ' + _lbl + ' style="margin-bottom:0">Team Name</label>\n'
        '    <input id="tb-team-name" placeholder="my-team" ' + _inp + ' style="width:180px;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px">\n'
        '    <button class="btn btn-accent" onclick="tbGenerateTeam()">&#x2699; Generate</button>\n'
        '    <button class="btn" onclick="tbCopyTeam()">&#x1f4cb; Copy</button>\n'
        '    <button class="btn" onclick="tbSaveTeam()">&#x1f4be; Save</button>\n'
        '    <span id="tb-save-status" style="font-size:12px"></span>\n'
        '  </div>\n'
        # Saved teams
        '  <div style="margin-top:16px">\n'
        '    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:6px">\n'
        '      <h4 style="font-size:13px;font-weight:600">Saved Teams</h4>\n'
        '      <button class="btn" style="font-size:11px" onclick="tbLoadSavedTeams()">&#x21bb; Refresh</button>\n'
        '    </div>\n'
        '    <div id="tb-saved-teams"></div>\n'
        '  </div>\n'
        '</div>\n'
    )


def _agent_crafter() -> str:
    _inp = 'style="width:100%;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px;font-family:var(--font-mono)"'
    _lbl = 'style="font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted);display:block;margin-bottom:4px"'
    return (
        '<div id="tab-agent-crafter" class="card" style="display:none">\n'
        '  <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px">\n'
        '    <h3 style="font-size:1rem;font-weight:600">&#x1f9d9; Agent Crafter</h3>\n'
        '    <span id="ac-count" style="font-size:12px;color:var(--text-muted)">0 agents</span>\n'
        '  </div>\n'
        # Filter + table
        '  <div style="display:flex;gap:8px;margin-bottom:10px">\n'
        '    <input id="ac-filter" placeholder="Filter agents…" oninput="acFilterAgents()" ' + _inp + ' style="flex:1;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px"/>\n'
        '  </div>\n'
        '  <div id="ac-agents-table" style="margin-bottom:20px"></div>\n'
        # Create form
        '  <details style="margin-top:8px">\n'
        '    <summary style="cursor:pointer;font-size:13px;font-weight:600;margin-bottom:10px;color:var(--accent)">+ Create New Agent</summary>\n'
        '    <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px">\n'
        '      <div><label ' + _lbl + '>Name</label><input id="ac-name" placeholder="my-agent" ' + _inp + '></div>\n'
        '      <div><label ' + _lbl + '>Model</label><input id="ac-model" placeholder="claude-sonnet-4-5" ' + _inp + '></div>\n'
        '      <div><label ' + _lbl + '>Description</label><input id="ac-desc" placeholder="One-line description" ' + _inp + '></div>\n'
        '      <div><label ' + _lbl + '>Max Turns</label><input id="ac-maxturns" type="number" value="25" ' + _inp + '></div>\n'
        '      <div><label ' + _lbl + '>MCP Servers (comma-sep)</label><input id="ac-mcp" placeholder="cybersec,dystopian" ' + _inp + '></div>\n'
        '    </div>\n'
        '    <div style="margin-top:10px">\n'
        '      <label ' + _lbl + '>Tools</label>\n'
        '      <div id="ac-tools" style="display:flex;flex-wrap:wrap;gap:8px;margin-top:4px">\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Read"> Read</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Write"> Write</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Glob"> Glob</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Grep"> Grep</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Bash"> Bash</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="WebFetch"> WebFetch</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="WebSearch"> WebSearch</label>\n'
        '      </div>\n'
        '    </div>\n'
        '    <div style="margin-top:10px">\n'
        '      <label ' + _lbl + '>Instructions</label>\n'
        '      <textarea id="ac-instructions" rows="4" placeholder="Agent persona and task instructions…" ' + _inp + '></textarea>\n'
        '    </div>\n'
        '    <div style="display:flex;align-items:center;gap:10px;margin-top:10px">\n'
        '      <button class="btn btn-accent" onclick="acCreateAgent()">Create Agent</button>\n'
        '      <span id="ac-status" style="font-size:12px"></span>\n'
        '    </div>\n'
        '  </details>\n'
        # Edit modal (hidden)
        '  <div id="ac-edit-modal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:200;display:none;align-items:center;justify-content:center">\n'
        '    <div style="background:var(--surface-1);border:1px solid var(--border);border-radius:10px;padding:24px;width:520px;max-height:80vh;overflow-y:auto">\n'
        '      <h4 style="font-size:14px;font-weight:600;margin-bottom:14px">Edit: <span id="ac-edit-name"></span></h4>\n'
        '      <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px">\n'
        '        <div><label ' + _lbl + '>Model</label><input id="ac-edit-model" ' + _inp + '></div>\n'
        '        <div><label ' + _lbl + '>Max Turns</label><input id="ac-edit-maxturns" type="number" ' + _inp + '></div>\n'
        '        <div style="grid-column:1/-1"><label ' + _lbl + '>Description</label><input id="ac-edit-desc" ' + _inp + '></div>\n'
        '      </div>\n'
        '      <label ' + _lbl + '>Instructions</label>\n'
        '      <textarea id="ac-edit-instructions" rows="6" ' + _inp + ' style="width:100%;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px;font-family:var(--font-mono)"></textarea>\n'
        '      <div style="display:flex;align-items:center;gap:10px;margin-top:12px">\n'
        '        <button class="btn btn-accent" onclick="acSaveEdit()">Save</button>\n'
        '        <button class="btn btn-ghost" onclick="acCloseEdit()">Cancel</button>\n'
        '        <span id="ac-edit-status" style="font-size:12px"></span>\n'
        '      </div>\n'
        '    </div>\n'
        '  </div>\n'
        '</div>\n'
    )


def _agent_factory() -> str:
    _inp = 'style="width:100%;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px;font-family:var(--font-mono)"'
    _lbl = 'style="font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted);display:block;margin-bottom:4px"'
    return (
        '<div id="tab-agent-factory" class="card" style="display:none">\n'
        '  <h3 style="font-size:1rem;font-weight:600;margin-bottom:12px">&#x1f4ed; Agent Factory</h3>\n'
        # Stats section populated by refresh.ts
        '  <div id="agent-factory-content" style="margin-bottom:20px;color:var(--text-muted)">Loading agent factory…</div>\n'
        # Generate form
        '  <details open style="margin-top:4px">\n'
        '    <summary style="cursor:pointer;font-size:13px;font-weight:600;margin-bottom:12px;color:var(--accent)">Generate New Agent</summary>\n'
        '    <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px">\n'
        '      <div><label ' + _lbl + '>Agent Name</label><input id="af-name" placeholder="my-specialist" ' + _inp + '></div>\n'
        '      <div>\n'
        '        <label ' + _lbl + '>Type</label>\n'
        '        <select id="af-type" ' + _inp + '>\n'
        '          <option value="specialist">Specialist</option>\n'
        '          <option value="team-leader">Team Leader</option>\n'
        '          <option value="orchestrator">Orchestrator</option>\n'
        '        </select>\n'
        '        <span id="af-type-hint" style="font-size:11px;color:var(--text-muted);display:block;margin-top:3px"></span>\n'
        '      </div>\n'
        '      <div>\n'
        '        <label ' + _lbl + '>Model</label>\n'
        '        <select id="af-model" ' + _inp + '>\n'
        '          <option value="sonnet">claude-sonnet-4-5</option>\n'
        '          <option value="haiku">claude-haiku-4-5</option>\n'
        '          <option value="opus">claude-opus-4-5</option>\n'
        '        </select>\n'
        '      </div>\n'
        '      <div><label ' + _lbl + '>Max Turns</label><input id="af-maxturns" type="number" value="30" ' + _inp + '></div>\n'
        '      <div style="grid-column:1/-1"><label ' + _lbl + '>Description</label><textarea id="af-desc" rows="2" placeholder="What this agent does…" ' + _inp + '></textarea></div>\n'
        '    </div>\n'
        # Tools
        '    <div style="margin-top:12px">\n'
        '      <label ' + _lbl + '>Tools</label>\n'
        '      <div id="af-tools" style="display:flex;flex-wrap:wrap;gap:8px;margin-top:4px">\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Read" checked> Read</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Write"> Write</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Glob" checked> Glob</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Grep" checked> Grep</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="Bash"> Bash</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="WebFetch"> WebFetch</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" value="WebSearch"> WebSearch</label>\n'
        '      </div>\n'
        '    </div>\n'
        # Research (af-r-*)
        '    <div style="margin-top:12px">\n'
        '      <label ' + _lbl + '>Research Context</label>\n'
        '      <div style="display:flex;flex-wrap:wrap;gap:8px;margin-top:4px">\n'
        '        <label style="font-size:12px"><input type="checkbox" id="af-r-mitre" value="mitre"> MITRE ATT&amp;CK</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" id="af-r-cve" value="cve"> CVE/NVD</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" id="af-r-owasp" value="owasp"> OWASP</label>\n'
        '        <label style="font-size:12px"><input type="checkbox" id="af-r-nist" value="nist"> NIST CSF</label>\n'
        '      </div>\n'
        '    </div>\n'
        # Base templates + skills
        '    <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px">\n'
        '      <div>\n'
        '        <label ' + _lbl + '>Base Template</label>\n'
        '        <div style="display:flex;gap:6px;align-items:center">\n'
        '          <select id="af-tpl-0" ' + _inp + ' style="flex:1;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px"><option value="">— none —</option></select>\n'
        '          <button class="btn" style="font-size:11px;padding:3px 8px" onclick="afAddTemplate()">+</button>\n'
        '        </div>\n'
        '        <div id="af-tpl-rows" style="margin-top:4px;display:flex;flex-direction:column;gap:4px"></div>\n'
        '      </div>\n'
        '      <div>\n'
        '        <label ' + _lbl + '>Skill</label>\n'
        '        <div style="display:flex;gap:6px;align-items:center">\n'
        '          <select id="af-skill-0" ' + _inp + ' style="flex:1;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px"><option value="">— none —</option></select>\n'
        '          <button class="btn" style="font-size:11px;padding:3px 8px" onclick="afAddSkill()">+</button>\n'
        '        </div>\n'
        '        <div id="af-skill-rows" style="margin-top:4px;display:flex;flex-direction:column;gap:4px"></div>\n'
        '      </div>\n'
        '    </div>\n'
        # Extra instructions
        '    <div style="margin-top:10px">\n'
        '      <label ' + _lbl + '>Extra Instructions</label>\n'
        '      <textarea id="af-extra" rows="3" placeholder="Additional instructions or constraints…" ' + _inp + '></textarea>\n'
        '    </div>\n'
        # Options + actions
        '    <div style="display:flex;align-items:center;flex-wrap:wrap;gap:14px;margin-top:12px">\n'
        '      <label style="font-size:12px"><input type="checkbox" id="af-save-file" checked> Save to .claude/agents/</label>\n'
        '      <label style="font-size:12px"><input type="checkbox" id="af-project-ctx"> Include project context</label>\n'
        '      <button class="btn btn-accent" onclick="afGenerate()">&#x2699; Generate</button>\n'
        '      <span id="af-status" style="font-size:12px"></span>\n'
        '    </div>\n'
        '    <pre id="af-preview" style="display:none;margin-top:14px;padding:12px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);font-size:11px;overflow-x:auto;white-space:pre-wrap;word-break:break-word;color:var(--text-primary)"></pre>\n'
        '  </details>\n'
        '</div>\n'
    )


def _workflows() -> str:
    _inp = 'style="padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px;font-family:var(--font-mono)"'
    return (
        '<div id="tab-workflows" class="card" style="display:none">\n'
        '  <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:14px">\n'
        '    <h3 style="font-size:1rem;font-weight:600">&#x21c4; Workflows</h3>\n'
        '    <div style="display:flex;gap:8px">\n'
        '      <input id="wf-name" placeholder="Workflow name…" ' + _inp + ' style="width:200px;padding:6px 10px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);font-size:12px">\n'
        '      <button class="btn" onclick="wfAddStep()">+ Add Step</button>\n'
        '      <button class="btn btn-accent" onclick="wfExecute()">&#x25b6; Execute</button>\n'
        '      <button class="btn btn-ghost" onclick="wfClear()">&#x2715; Clear</button>\n'
        '    </div>\n'
        '  </div>\n'
        '  <div id="wf-steps" style="display:flex;flex-direction:column;gap:10px;min-height:60px;margin-bottom:14px"></div>\n'
        '  <div style="display:flex;align-items:center;gap:10px;margin-bottom:10px">\n'
        '    <span id="wf-status" style="font-size:12px;font-family:var(--font-mono)"></span>\n'
        '  </div>\n'
        '  <div id="wf-output" style="display:none;margin-top:8px">\n'
        '    <h4 style="font-size:13px;font-weight:600;margin-bottom:8px">Results</h4>\n'
        '    <div id="wf-result-steps" style="display:flex;flex-direction:column;gap:8px"></div>\n'
        '  </div>\n'
        '  <datalist id="wf-agent-list"></datalist>\n'
        '</div>\n'
    )


def _flowgraph() -> str:
    return tab_panel(
        "flowgraph",
        "&#x2b61; Flowgraph",
        '<div id="flowgraph-container" style="display:flex;gap:16px;height:calc(100vh - 200px)">'
        '<div id="flowgraph-palette" style="width:180px;border:1px solid var(--border);border-radius:6px;padding:8px;overflow-y:auto">'
        '<div style="font-size:11px;color:var(--text-muted);margin-bottom:8px">Drag agents to canvas</div>'
        '<div id="fg-agent-list" style="display:flex;flex-direction:column;gap:4px"></div>'
        '</div>'
        '<div id="drawflow" style="flex:1;border:1px solid var(--border);border-radius:6px;background:var(--surface-2);position:relative;overflow:hidden"></div>'
        '</div>'
        '<div id="flowgraph-log" class="space-y-2" style="margin-top:16px;max-height:120px;overflow-y:auto;border:1px solid var(--border);padding:8px;border-radius:6px;font-family:var(--font-mono);font-size:10px"></div>'
        '<style>'
        '#drawflow { background-image: '
        'linear-gradient(0deg, transparent 23px, var(--border) 24px), '
        'linear-gradient(90deg, transparent 23px, var(--border) 24px); '
        'background-size: 24px 24px; }'
        '.drawflow-node { background: var(--surface); border: 1px solid var(--accent); }'
        '.drawflow-node.selected { background: var(--accent-glow); border-color: var(--accent); }'
        '</style>',
    )


def _sdk_lab() -> str:
    """TypeScript SDK Lab panel — streaming, tools, structured, thinking, memory."""
    _S = 'background:var(--surface-2);border:1px solid var(--border);color:var(--text-primary)'
    _PRE = f'style="{_S};border-radius:8px;padding:12px;min-height:100px;font-size:11px;white-space:pre-wrap;overflow-y:auto;max-height:260px"'
    _AREA = f'class="w-full px-3 py-2 text-sm rounded-lg outline-none" style="{_S}"'
    _INP = f'class="w-full px-3 py-2 text-sm rounded-lg outline-none mb-2" style="{_S}"'
    _LBL = 'class="text-xs uppercase tracking-wide block mb-1" style="color:var(--text-muted)"'
    _ST = 'style="font-size:11px;min-height:1.2em;margin-top:4px" '
    return (
        '<div id="tab-sdk-lab" class="card" style="display:none">\n'
        f'  <div class="flex items-center justify-between mb-3">\n'
        f'    <h3 class="text-lg font-semibold">&#x2297; SDK Lab</h3>\n'
        f'    <span id="sdk-api-health" {_ST}style="color:var(--text-muted);font-size:11px;cursor:pointer" onclick="sdkApiHealth()">TS API (click to check)</span>\n'
        f'  </div>\n'
        # Sub-tab nav
        f'  <div id="sdk-sub-tabs" class="flex gap-2 mb-4 flex-wrap">\n'
        f'    <button class="btn btn-accent text-xs" onclick="sdkSubTab(\'stream\')">Stream</button>\n'
        f'    <button class="btn btn-ghost text-xs" onclick="sdkSubTab(\'tools\')">Tools</button>\n'
        f'    <button class="btn btn-ghost text-xs" onclick="sdkSubTab(\'structured\')">Structured</button>\n'
        f'    <button class="btn btn-ghost text-xs" onclick="sdkSubTab(\'thinking\')">Thinking</button>\n'
        f'    <button class="btn btn-ghost text-xs" onclick="sdkSubTab(\'memory\')">Memory</button>\n'
        f'  </div>\n'
        # Stream
        f'  <div id="sdk-sub-stream" class="sdk-sub">\n'
        f'    <div class="grid grid-cols-1 md:grid-cols-3 gap-3 mb-2">\n'
        f'      <div class="md:col-span-2"><label {_LBL}>Prompt</label>\n'
        f'        <textarea id="sdk-stream-input" rows="3" {_AREA} placeholder="Streaming prompt…">Explain XSS attacks in 3 sentences.</textarea></div>\n'
        f'      <div><label {_LBL}>Actions</label>\n'
        f'        <button class="btn btn-accent w-full text-xs mb-2" onclick="sdkStreamRun()">&#x25B6; Stream</button>\n'
        f'        <div id="sdk-stream-status" {_ST}style="color:var(--text-muted)"></div></div>\n'
        f'    </div>\n'
        f'    <pre id="sdk-stream-output" {_PRE}></pre>\n'
        f'  </div>\n'
        # Tools
        f'  <div id="sdk-sub-tools" class="sdk-sub" style="display:none">\n'
        f'    <div class="grid grid-cols-1 md:grid-cols-3 gap-3 mb-2">\n'
        f'      <div class="md:col-span-2"><label {_LBL}>Prompt</label>\n'
        f'        <textarea id="sdk-tools-input" rows="3" {_AREA} placeholder="Tool use prompt…">Search for recent CVEs in OpenSSL.</textarea></div>\n'
        f'      <div><label {_LBL}>Actions</label>\n'
        f'        <button class="btn btn-accent w-full text-xs mb-2" onclick="sdkToolsRun()">&#x25B6; Run Tools</button>\n'
        f'        <div id="sdk-tools-status" {_ST}style="color:var(--text-muted)"></div></div>\n'
        f'    </div>\n'
        f'    <label {_LBL}>Tools JSON (optional override)</label>\n'
        f'    <textarea id="sdk-tools-config" rows="2" {_AREA} placeholder="[]"></textarea>\n'
        f'    <pre id="sdk-tools-output" {_PRE} style="margin-top:8px"></pre>\n'
        f'  </div>\n'
        # Structured
        f'  <div id="sdk-sub-structured" class="sdk-sub" style="display:none">\n'
        f'    <div class="grid grid-cols-1 md:grid-cols-3 gap-3 mb-2">\n'
        f'      <div class="md:col-span-2"><label {_LBL}>Text to parse</label>\n'
        f'        <textarea id="sdk-struct-input" rows="3" {_AREA} placeholder="Text to extract IOCs from…">The malware connected to 192.168.1.1 and dropped evil.exe, also visited https://malware.example.com.</textarea></div>\n'
        f'      <div><label {_LBL}>Schema</label>\n'
        f'        <select id="sdk-struct-schema" {_INP}>\n'
        f'          <option value="ioc_extraction">IOC Extraction</option>\n'
        f'          <option value="finding_classification">Finding Classification</option>\n'
        f'          <option value="threat_actor">Threat Actor</option>\n'
        f'          <option value="cve_context">CVE Context</option>\n'
        f'          <option value="generic_json">Generic JSON</option>\n'
        f'        </select>\n'
        f'        <button class="btn btn-accent w-full text-xs mb-2" onclick="sdkStructuredRun()">&#x25B6; Extract</button>\n'
        f'        <div id="sdk-struct-status" {_ST}style="color:var(--text-muted)"></div></div>\n'
        f'    </div>\n'
        f'    <pre id="sdk-struct-output" {_PRE}></pre>\n'
        f'  </div>\n'
        # Thinking
        f'  <div id="sdk-sub-thinking" class="sdk-sub" style="display:none">\n'
        f'    <div class="grid grid-cols-1 md:grid-cols-3 gap-3 mb-2">\n'
        f'      <div class="md:col-span-2"><label {_LBL}>Complex prompt</label>\n'
        f'        <textarea id="sdk-think-input" rows="3" {_AREA} placeholder="Complex reasoning prompt…">Analyse the attack chain: initial access via spear-phishing, lateral movement using PsExec, ransomware deployment. What TTPs?</textarea></div>\n'
        f'      <div><label {_LBL}>Budget tokens</label>\n'
        f'        <input id="sdk-think-budget" type="number" value="8000" min="1024" max="32000" step="1024" {_INP} />\n'
        f'        <button class="btn btn-accent w-full text-xs mb-2" onclick="sdkThinkingRun()">&#x25B6; Think</button>\n'
        f'        <div id="sdk-think-status" {_ST}style="color:var(--text-muted)"></div></div>\n'
        f'    </div>\n'
        f'    <label {_LBL}>Thinking</label>\n'
        f'    <pre id="sdk-think-thinking" {_PRE} style="opacity:0.6;max-height:120px"></pre>\n'
        f'    <label {_LBL} style="margin-top:8px">Answer</label>\n'
        f'    <pre id="sdk-think-answer" {_PRE} style="margin-top:4px"></pre>\n'
        f'  </div>\n'
        # Memory
        f'  <div id="sdk-sub-memory" class="sdk-sub" style="display:none">\n'
        f'    <div class="grid grid-cols-1 md:grid-cols-3 gap-3 mb-2">\n'
        f'      <div class="md:col-span-2"><label {_LBL}>Prompt (memory-aware)</label>\n'
        f'        <textarea id="sdk-mem-input" rows="3" {_AREA} placeholder="Memory-aware prompt…">Remember that APT29 uses Cobalt Strike. Then tell me what you know about APT29.</textarea></div>\n'
        f'      <div style="display:flex;flex-direction:column;gap:8px">\n'
        f'        <button class="btn btn-accent text-xs" onclick="sdkMemoryRun()">&#x25B6; Run + Store</button>\n'
        f'        <button class="btn btn-ghost text-xs" onclick="sdkMemoryRead()">&#x1f4c4; Read Memories</button>\n'
        f'        <div id="sdk-mem-status" {_ST}style="color:var(--text-muted)"></div></div>\n'
        f'    </div>\n'
        f'    <pre id="sdk-mem-output" {_PRE}></pre>\n'
        f'    <label {_LBL} style="margin-top:8px">Memory store content</label>\n'
        f'    <pre id="sdk-mem-content" {_PRE} style="margin-top:4px;opacity:0.8"></pre>\n'
        f'  </div>\n'
        f'</div>\n'
    )


