#!/usr/bin/env python3
"""
YARA Rule Generator Hook – MalwareHunter
Generates high-quality YARA rules from IOCs, findings, suspicious strings,
memory patterns, binary artifacts, and threat intelligence.
"""

import asyncio
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from utils import ensure_structure, get_session_dir
from uvloop_integration import run_with_uvloop


async def yara_rule_generator_async():
    """Generate YARA rules from current session data"""

    # Get input from environment or stdin
    session_dir = get_session_dir()
    investigation_id = os.environ.get('MALWARE_INVESTIGATION_ID', datetime.now().strftime('%Y%m%d_%H%M%S'))
    trigger_type = os.environ.get('YARA_TRIGGER_TYPE', sys.argv[1] if len(sys.argv) > 1 else 'ioc_discovered')

    ensure_structure()

    # Collect data sources for rule generation
    sources = {
        "iocs": [],
        "findings": [],
        "suspicious_strings": [],
        "memory_patterns": [],
        "binary_hashes": [],
        "threat_details": os.environ.get('MALWARE_THREAT_TYPE', 'Unknown')
    }

    if session_dir:
        # Read IOCs
        ioc_dir = session_dir / investigation_id / "iocs"
        if ioc_dir.exists():
            for f in ioc_dir.glob("*.json"):
                try:
                    data = json.loads(f.read_text())
                    if isinstance(data, list):
                        sources["iocs"].extend(data)
                    elif isinstance(data, dict):
                        sources["iocs"].append(data)
                except:
                    continue

        # Read findings
        findings_file = session_dir / "findings.md"
        if findings_file.exists():
            sources["findings"] = findings_file.read_text(encoding="utf-8")

    # Generate YARA rules
    rules = generate_yara_rules(sources)

    # Save rules
    if session_dir:
        yara_dir = session_dir / investigation_id / "yara"
        yara_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        rule_file = yara_dir / f"generated_rules_{timestamp}.yar"

        rule_file.write_text(rules, encoding="utf-8")

        # Also save to project level
        project_yara = Path(os.environ.get("CLAUDE_PLUGIN_DATA", "/tmp")) / "cybersec-mem/project/yara"
        project_yara.mkdir(parents=True, exist_ok=True)
        (project_yara / f"rules_{timestamp}.yar").write_text(rules, encoding="utf-8")

    # Output for Claude
    output = {
        "hookSpecificOutput": {
            "additionalContext": f"""🛠️ **YARA RULE GENERATION COMPLETE**

**Trigger:** {trigger_type}
**Rules Generated:** {rules.count('rule ')}
**Session:** {session_dir.name if session_dir else 'N/A'}
**Saved to:** {yara_dir if session_dir else 'Project level'}

**Generated Rules:**
{rules}

**Next Steps:**
• Test rules with `yara -r generated_rules_*.yar <target>`
• Add to watchlist if high-confidence
• Share to shared-memory layer"""
        }
    }

    print(json.dumps(output))


def generate_yara_rules(sources):
    """Generate high-quality YARA rules from collected data"""
    rules = "/*\n"
    rules += f"YARA Rules Generated by MalwareHunter - {datetime.now().isoformat()}\n"
    rules += f"Threat: {sources.get('threat_details', 'Unknown')}\n"
    rules += "*/\n\n"

    # Rule 1: IOC-based rules
    if sources["iocs"]:
        rules += "/* IOC-based detection rules */\n"
        for ioc in sources["iocs"][:10]:  # Limit to avoid huge rules
            if isinstance(ioc, dict) and ioc.get("value"):
                value = ioc["value"]
                ioc_type = ioc.get("type", "unknown")
                if len(value) > 8:  # Only meaningful strings
                    rules += f'rule IOC_{ioc_type.upper()}_{hash(value) % 10000:04d} {{\n'
                    rules += '    meta:\n'
                    rules += f'        description = "MalwareHunter IOC match - {ioc_type}"\n'
                    rules += f'        confidence = "high"\n'
                    rules += '    strings:\n'
                    if ioc_type in ["file_hash", "sha256"]:
                        rules += f'        $hash = "{value}" ascii\n'
                    else:
                        rules += f'        $str = "{value}" ascii wide\n'
                    rules += '    condition:\n'
                    rules += '        any of them\n'
                    rules += '}\n\n'

    # Rule 2: Suspicious strings / memory patterns
    rules += "/* Suspicious string patterns from memory / logs */\n"
    common_suspicious = ["mimikatz", "psexec", "krbtgt", "LD_PRELOAD", "screenshot", "exfil", "c2", "beacon"]
    for s in common_suspicious:
        rules += f'rule Suspicious_String_{s.upper()} {{\n'
        rules += '    meta:\n'
        rules += f'        description = "Suspicious string often used by APT/rootkits: {s}"\n'
        rules += '        confidence = "medium"\n'
        rules += '    strings:\n'
        rules += f'        $s = "{s}" ascii wide nocase\n'
        rules += '    condition:\n'
        rules += '        any of them\n'
        rules += '}\n\n'

    # Rule 3: Browser / session hijacking patterns
    rules += "/* Browser session hijacking / cookie theft patterns */\n"
    rules += 'rule Browser_Hijacking_Indicators {\n'
    rules += '    meta:\n'
    rules += '        description = "Browser session hijacking or cookie theft patterns"\n'
    rules += '        confidence = "high"\n'
    rules += '    strings:\n'
    rules += '        $cookie1 = "document.cookie" ascii wide\n'
    rules += '        $cookie2 = "sessionStorage" ascii wide\n'
    rules += '        $exfil = "exfil" ascii wide nocase\n'
    rules += '        $screenshot = "screenshot" ascii wide nocase\n'
    rules += '    condition:\n'
    rules += '        2 of them\n'
    rules += '}\n\n'

    return rules


def main():
    run_with_uvloop(yara_rule_generator_async())


if __name__ == "__main__":
    main()